### ISSUE TITLE
Can't add a search result to a list on click

### ISSUE THREAD

**Issue by trivett** [trivett/tangochan#1]
This in words/search.js.erb

```
<% @results.each do |r| %>
   var word = $("<div>  <p><%=j r.kanji %></p><p><%=j r.kana %></p><p><%=j r.english %></p></div>").fadeIn(500);

   console.log("<%=j r.english %>");
   console.log("<%= @list.id %>");
   word.addClass("show-word");
   word.appendTo("#word-results");

 <% end %>

```

gives us the proper search results appended to the DOM. Nice. But we want to add the user's chosen word to `@list`.

if we put in 
`<% @list <<  r %>` in the middle of the loop, it works, but we want that to work on clicking a button.

We've both tried adding a form with hidden fields such as.... 

```
<%= form_for(@list) do |f| %>
<%= f.hidden_field :word r  %>
<%= f.submit("Add to List") %>
<% end %></div>
```

 and functions in the relevant js.coffee files but we can't even get them to display in the div for each search result. It seems that we rarely get a useful error out of the console, if any at all. This sounds really simple, but we have put about 8 person-hours on it. We appreciate some help.

**Comment by harimohanraj89** [comment]
Remember to stay conscious of which language space you're working in. If you were trying to generate html, then `form_for`s and such would the the right approach. However, it looks like you're trying to generate some javascript that will append a form to the page. Hence, you may need to do something like

``` js
var formHtml = "<%= j(render partial: add_to_list) %>";
$('#word').append(formHtml);
```

and ensure that your `form_for` stuff is inside a .html.erb partial file.
