### ISSUE TITLE
infinite loop between javascript functions

### ISSUE THREAD

**Issue by ddigioia** [trivett/tangochan#15]
I'm running into the problem of passing a variable from one function to another without creating an infinite loop between the two functions. The first function (startTest) calls the second function (submitAnswer) when the submit button is clicked. However I need to pass a variable into the submitAnswer function, so instead of setting the event handler of the submit button to: 

```
 submitAnswerButton.click(submitAnswer);
```

I changed it to:

```
 submitAnswerButton.click(submitAnswer(realAnswer);
```

This then calls the submitAnswer function, passing the variable that I want to pass but it also creates an infinite loop because submitAnswer then calls startTest:

function submitAnswer(){
  var flashCard = $(".flashCard");

  console.log($('#englishAnswer').text());

  storeAnswers();
  startTest();
}

If i declare a variable higher in scope, outside the functions, for some reason I cannot reference that variable from the submitAnswer function. I'm not sure why this is. Any suggestions?

**Comment by harimohanraj89** [comment]
We discussed this in person. Closing this issue.
