### ISSUE TITLE
One step behind

### ISSUE THREAD

**Issue by ddigioia** [trivett/tangochan#23]
This issue is in the view/lists/test.js.erb file.

Not understanding why in my spaghetti mess of a JS file the correct english answer is a step behind the user answer. In the startTest function the realAnswer variable is the current english answer to the word that displays on the first flashcard. But the rest of the tests are one realAnswer behind the current flashcard realAnswer, so the user will always be wrong.

I have duplicated code in the startTest function and refreshFlashCard, which I have to dry up, but basically the startTest function creates the first flashcard and every flashcard after the first is created by the refreshFlashCard function. It will eventually be one function but for now its a sloppy two. This may be the issue?

**Comment by harimohanraj89** [comment]
I spoke with you regarding this. Try reworking your javascript based on our discussion. I will leave this issue open for if you still have trouble. If you fix things, go ahead and close this issue.
