### ISSUE TITLE
304 not modified error, page apparently coming back cached after one search

### ISSUE THREAD

**Issue by trivett** [trivett/tangochan#8]
The search button is not able to reload because it thinks that the page is unchanged after adding a word to the list. Here is the form that adds the word to list: 

```
<%= form_tag "/add_to_list", :method => "post", remote: true do %>
  <%= hidden_field_tag :word_id, word.id %>
  <%= hidden_field_tag :list_id, @list.id %>
  <%= submit_tag "Add to list", :class =>"button" %>
<% end %>
```

Which corresponds to this controller action: 

```
  def add_to_list
    @word = Word.find(params[:word_id])
    @list = List.find(params[:list_id])
    @list.words << @word
    response.cache_control.replace(:no_cache => true)
    respond_to do |format|
      format.js { }
    end
  end
```

And this view:

```
var word = $("<%= j(render @word) %>");
// console.log(word);
$('#list-words-display ul').append(word);
var wordResults = $('#word-results');
wordResults.fadeOut(250);
```

If you add one to the list, it successfully updates the database and appends the card to the relevant place in the DOM. But if you return to the search bar and press the search button, it does nothing and gives you a 304 error. 

Is there some way of having the page refresh without having to reload?

**Comment by harimohanraj89** [comment]
Resolved.
